### ISSUE TITLE
qr code not working

### ISSUE THREAD

**Issue by abhijit826** [powercomp750/UPI-QR-Generator#1]
bro your qr code not working on any upi apps

**Comment by powercomp750** [comment]
What is the issue you are facing?

**Comment by abhijit826** [comment]
qr not scanning

**Comment by powercomp750** [comment]
I think there is some issues with QR implementation, looks like NPCI has implemented new policies which is causing issues in generation of static QR codes. I try to fix it or else there will be new one completely written from scratch.

However you can use Google Pay application, it is able to scan QR codes, other apps have issues.
